services:
  front:
    container_name: hiremate-front
    build:
      context: ../hiremate-front
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
     - public_network
    restart: always
  api:
    container_name: hiremate-api
    build: 
      context: ../hiremate-api
      dockerfile: Dockerfile.dev
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
    networks:
      - public_network
      - private_network
    restart: always
networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge
